-- MySQL Script generated by MySQL Workbench
-- Mon Jan 25 09:41:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Blog` DEFAULT CHARACTER SET utf8 ;
USE `Blog` ;

-- -----------------------------------------------------
-- Table `Blog`.`Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog`.`Author` (
  `idAuthor` INT NOT NULL,
  `pseudo` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  PRIMARY KEY (`idAuthor`, `pseudo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blog`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog`.`Post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(250) NULL,
  `content` LONGTEXT NULL,
  `startdate` DATETIME NULL,
  `enddtae` DATETIME NULL,
  `weigth` VARCHAR(45) NULL,
  `Author_idAuthor` INT NOT NULL,
  `Author_pseudo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Post_Author1_idx` (`Author_idAuthor` ASC, `Author_pseudo` ASC) ,
  CONSTRAINT `fk_Post_Author1`
    FOREIGN KEY (`Author_idAuthor` , `Author_pseudo`)
    REFERENCES `Blog`.`Author` (`idAuthor` , `pseudo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blog`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog`.`Category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blog`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog`.`Comment` (
  `idComment` INT NOT NULL,
  `publicationdate` DATE NULL,
  `text` VARCHAR(255) NULL,
  `Author_idAuthor` INT NOT NULL,
  `Author_pseudo` VARCHAR(45) NOT NULL,
  `Post_id` INT NOT NULL,
  PRIMARY KEY (`idComment`),
  INDEX `fk_Comment_Author1_idx` (`Author_idAuthor` ASC, `Author_pseudo` ASC) ,
  INDEX `fk_Comment_Post1_idx` (`Post_id` ASC) ,
  CONSTRAINT `fk_Comment_Author1`
    FOREIGN KEY (`Author_idAuthor` , `Author_pseudo`)
    REFERENCES `Blog`.`Author` (`idAuthor` , `pseudo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Post1`
    FOREIGN KEY (`Post_id`)
    REFERENCES `Blog`.`Post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blog`.`post_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog`.`post_category` (
  `Post_id` INT NOT NULL,
  `Category_id` INT NOT NULL,
  INDEX `fk_post_category_Post1_idx` (`Post_id` ASC) ,
  INDEX `fk_post_category_Category1_idx` (`Category_id` ASC) ,
  CONSTRAINT `fk_post_category_Post1`
    FOREIGN KEY (`Post_id`)
    REFERENCES `Blog`.`Post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_category_Category1`
    FOREIGN KEY (`Category_id`)
    REFERENCES `Blog`.`Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
